name: Build and Push Docker Image

on:
  push:
    branches:
      - refactor
      - dev
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: npm run build:dockerx

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker tag chatgpt-telegram-workers:latest ${{ secrets.DOCKER_USERNAME }}/chatgpt-telegram-workers:${COMMIT_SHA}
          docker tag chatgpt-telegram-workers:latest ${{ secrets.DOCKER_USERNAME }}/chatgpt-telegram-workers:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chatgpt-telegram-workers:${COMMIT_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/chatgpt-telegram-workers:latest
